### ISSUE TITLE
add an option to reverse the stack order as a checkbox.

### ISSUE THREAD

**Issue by muratmaga** [pieper/SlicerImageStacks#7]
Since we cannot possibly know the slice ordering of every scanner vendor and dataset, this is probably the easiest option to deal with mirroring of the specimen (as long user knows what the specimen should look like).

Simple Filters->Flip Axes->Set Z axis bit and choose flip around origin achieves the same thing, but it would be good to do at the time of the import.

**Comment by pieper** [comment]
I thought we looked at this before and decided to suggest a negative Z spacing?  Perhaps a checkbox is more clear, but it's also possible to change the sort order of the files in the browse dialog box and they will load in the order they are displayed in the dialog.

Maybe instead of a checkbox we could include header columns in the file list that lets you reverse order by clicking.

**Comment by muratmaga** [comment]
I forgot about those options. But are they implemented? Right now, I cannot enter a negative value to Z spacing. Nor there is any indication that the file ordering can be reverse sorted. I still think a check box that says reverse image stack order is somewhat more informative than these two.

**Comment by pieper** [comment]
yes, the negative z works for me.  Just type it in - this doesn't work for you?

Reversing the load order depends on the file dialog I guess.  Some would support it and some not.

No, I didn't add sorting button.  We can easily add a checkbox to reverse.

**Comment by muratmaga** [comment]
Nope, can't enter a number after -
I wonder if this is a windows specific issue, along with the Export As issue I just filed
https://github.com/SlicerMorph/SlicerMorph/issues/56

**Comment by pieper** [comment]
That is odd, the negative z value works on mac but not on windows.  In any case yes, the checkbox is fine.
